// ABLLS-R Domain Colors for React Native
export const DOMAIN_COLORS_MAP = {
  'A': '#fee2e2', // red-100
  'B': '#fed7aa', // orange-100
  'C': '#fde68a', // amber-100
  'D': '#fef3c7', // yellow-100
  'E': '#d9f99d', // lime-100
  'F': '#bbf7d0', // green-100
  'G': '#a7f3d0', // emerald-100
  'H': '#a5f3fc', // teal-100
  'I': '#a5f0fc', // cyan-100
  'J': '#bae6fd', // sky-100
  'K': '#bfdbfe', // blue-100
  'L': '#c7d2fe', // indigo-100
  'M': '#ddd6fe', // violet-100
  'N': '#e9d5ff', // purple-100
  'O': '#f0abfc', // fuchsia-100
  'P': '#f9a8d4', // pink-100
  'Q': '#fda4af', // rose-100
  'R': '#fecaca', // red-200
  'S': '#fed1ae', // orange-200
  'T': '#fde291', // amber-200
  'U': '#fdf0a6', // yellow-200
  'V': '#ecfccb', // lime-200
  'W': '#bef264', // green-200
  'X': '#86efac', // emerald-200
  'Y': '#7dd3fc', // teal-200
  'Z': '#67e8f9', // cyan-200,
};

// ABLLS-R Skill Interface
export class ABLLSSkill {
  constructor(code, domain, number, description, longDescription = null) {
    this.code = code;
    this.domain = domain;
    this.number = number;
    this.description = description;
    this.longDescription = longDescription;
  }
}

// Program Target Interface
export class ProgramTarget {
  constructor(id, description, mastered, baselineDate = null, teachingDate = null, masteryDate = null, dataCollectionMethod = null) {
    this.id = id;
    this.description = description;
    this.mastered = mastered;
    this.baselineDate = baselineDate;
    this.teachingDate = teachingDate;
    this.masteryDate = masteryDate;
    this.dataCollectionMethod = dataCollectionMethod;
  }
}

// Data Collection Method Types
export const DATA_COLLECTION_METHODS = {
  FREQUENCY: 'frequency',
  DURATION: 'duration',
  TRIAL_BY_TRIAL: 'trial-by-trial',
  RUBRIC: 'rubric',
  PROMPT_LEVEL: 'prompt-level'
};

// Program Interface (both ABLLS-R and Custom)
export class Program {
  constructor(id, childId, therapistId, title, code = null, domain = null, category = null, 
              shortDescription, longDescription = null, masteryCriteria = null, 
              dataCollectionMethod, targets = [], isActive = true, createdAt, updatedAt) {
    this.id = id;
    this.childId = childId;
    this.therapistId = therapistId;
    this.title = title;
    this.code = code;
    this.domain = domain;
    this.category = category;
    this.shortDescription = shortDescription;
    this.longDescription = longDescription;
    this.masteryCriteria = masteryCriteria;
    this.dataCollectionMethod = dataCollectionMethod;
    this.targets = targets;
    this.isActive = isActive;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.archivedAt = null;
  }
}

// Therapist Specialty Types
export const THERAPIST_SPECIALTIES = {
  ABA: 'aba',
  SPEECH: 'speech',
  OT: 'ot',
  PT: 'pt',
  BEHAVIOR_ANALYST: 'behavior-analyst'
};

// Complete ABLLS-R Skills Database (all 25 domains)
export const ABLLS_SKILLS = [
  // Domain A: Cooperation & Reinforcer Effectiveness (A1-A19)
  new ABLLSSkill('A1', 'A', 1, 'Reinforcer effectiveness'),
  new ABLLSSkill('A2', 'A', 2, 'Cooperation'),
  new ABLLSSkill('A3', 'A', 3, 'Seeks attention appropriately'),
  new ABLLSSkill('A4', 'A', 4, 'Accepts interruption of reinforcer delivery'),
  new ABLLSSkill('A5', 'A', 5, 'Accepts interruption of activity'),
  new ABLLSSkill('A6', 'A', 6, 'Tolerates delays in reinforcement'),
  new ABLLSSkill('A7', 'A', 7, 'Tolerates transition from preferred to non-preferred activities'),
  new ABLLSSkill('A8', 'A', 8, 'Accepts redirection'),
  new ABLLSSkill('A9', 'A', 9, 'Tolerates physical guidance'),
  new ABLLSSkill('A10', 'A', 10, 'Tolerates physical restraint'),
  new ABLLSSkill('A11', 'A', 11, 'Tolerates verbal correction'),
  new ABLLSSkill('A12', 'A', 12, 'Tolerates denial of reinforcement'),
  new ABLLSSkill('A13', 'A', 13, 'Tolerates denial of tangible items'),
  new ABLLSSkill('A14', 'A', 14, 'Follows instructions'),
  new ABLLSSkill('A15', 'A', 15, 'Observes instructor for feedback'),
  new ABLLSSkill('A16', 'A', 16, 'Looks toward speaker'),
  new ABLLSSkill('A17', 'A', 17, 'Looks toward reinforcing item'),
  new ABLLSSkill('A18', 'A', 18, 'Looks toward reinforcing activity'),
  new ABLLSSkill('A19', 'A', 19, 'Looks toward peer'),

  // Domain B: Visual Performance (B1-B27)
  new ABLLSSkill('B1', 'B', 1, 'Visual attending'),
  new ABLLSSkill('B2', 'B', 2, 'Visual tracking'),
  new ABLLSSkill('B3', 'B', 3, 'Visual discrimination - identical'),
  new ABLLSSkill('B4', 'B', 4, 'Visual discrimination - different'),
  new ABLLSSkill('B5', 'B', 5, 'Visual discrimination - size'),
  new ABLLSSkill('B6', 'B', 6, 'Visual discrimination - color'),
  new ABLLSSkill('B7', 'B', 7, 'Visual discrimination - shape'),
  new ABLLSSkill('B8', 'B', 8, 'Visual discrimination - form'),
  new ABLLSSkill('B9', 'B', 9, 'Visual discrimination - picture'),
  new ABLLSSkill('B10', 'B', 10, 'Visual discrimination - photograph'),
  new ABLLSSkill('B11', 'B', 11, 'Visual discrimination - symbol'),
  new ABLLSSkill('B12', 'B', 12, 'Visual discrimination - written word'),
  new ABLLSSkill('B13', 'B', 13, 'Visual discrimination - environmental print'),
  new ABLLSSkill('B14', 'B', 14, 'Visual discrimination - abstract'),
  new ABLLSSkill('B15', 'B', 15, 'Visual closure'),
  new ABLLSSkill('B16', 'B', 16, 'Visual memory - identical'),
  new ABLLSSkill('B17', 'B', 17, 'Visual memory - different'),
  new ABLLSSkill('B18', 'B', 18, 'Visual memory - sequential'),
  new ABLLSSkill('B19', 'B', 19, 'Visual memory - spatial'),
  new ABLLSSkill('B20', 'B', 20, 'Visual memory - temporal'),
  new ABLLSSkill('B21', 'B', 21, 'Visual memory - categorical'),
  new ABLLSSkill('B22', 'B', 22, 'Visual memory - abstract'),
  new ABLLSSkill('B23', 'B', 23, 'Visual scanning'),
  new ABLLSSkill('B24', 'B', 24, 'Visual search'),
  new ABLLSSkill('B25', 'B', 25, 'Visual matching'),
  new ABLLSSkill('B26', 'B', 26, 'Visual assembly'),
  new ABLLSSkill('B27', 'B', 27, 'Visual construction'),

  // Domain C: Receptive Language (C1-C57)
  new ABLLSSkill('C1', 'C', 1, 'Receptive labels - body parts'),
  new ABLLSSkill('C2', 'C', 2, 'Receptive labels - common objects'),
  new ABLLSSkill('C3', 'C', 3, 'Receptive labels - foods'),
  new ABLLSSkill('C4', 'C', 4, 'Receptive labels - clothing'),
  new ABLLSSkill('C5', 'C', 5, 'Receptive labels - school items'),
  new ABLLSSkill('C6', 'C', 6, 'Receptive labels - rooms'),
  new ABLLSSkill('C7', 'C', 7, 'Receptive labels - outdoor items'),
  new ABLLSSkill('C8', 'C', 8, 'Receptive labels - vehicles'),
  new ABLLSSkill('C9', 'C', 9, 'Receptive labels - animals'),
  new ABLLSSkill('C10', 'C', 10, 'Receptive labels - people'),
  new ABLLSSkill('C11', 'C', 11, 'Receptive labels - actions'),
  new ABLLSSkill('C12', 'C', 12, 'Receptive labels - descriptive features'),
  new ABLLSSkill('C13', 'C', 13, 'Receptive labels - pronouns'),
  new ABLLSSkill('C14', 'C', 14, 'Receptive labels - prepositions'),
  new ABLLSSkill('C15', 'C', 15, 'Receptive labels - verbs'),
  new ABLLSSkill('C16', 'C', 16, 'Receptive labels - adjectives'),
  new ABLLSSkill('C17', 'C', 17, 'Receptive labels - adverbs'),
  new ABLLSSkill('C18', 'C', 18, 'Receptive labels - quantifiers'),
  new ABLLSSkill('C19', 'C', 19, 'Receptive labels - question words'),
  new ABLLSSkill('C20', 'C', 20, 'Receptive labels - categories'),
  new ABLLSSkill('C21', 'C', 21, 'Receptive labels - functions'),
  new ABLLSSkill('C22', 'C', 22, 'Receptive labels - attributes'),
  new ABLLSSkill('C23', 'C', 23, 'Receptive labels - abstract concepts'),
  new ABLLSSkill('C24', 'C', 24, 'Receptive actions - single step'),
  new ABLLSSkill('C25', 'C', 25, 'Receptive actions - two steps'),
  new ABLLSSkill('C26', 'C', 26, 'Receptive actions - three steps'),
  new ABLLSSkill('C27', 'C', 27, 'Receptive actions - conditional'),
  new ABLLSSkill('C28', 'C', 28, 'Receptive actions - chained'),
  new ABLLSSkill('C29', 'C', 29, 'Receptive actions - novel'),
  new ABLLSSkill('C30', 'C', 30, 'Receptive identification - body parts'),
  new ABLLSSkill('C31', 'C', 31, 'Receptive identification - common objects'),
  new ABLLSSkill('C32', 'C', 32, 'Receptive identification - foods'),
  new ABLLSSkill('C33', 'C', 33, 'Receptive identification - clothing'),
  new ABLLSSkill('C34', 'C', 34, 'Receptive identification - school items'),
  new ABLLSSkill('C35', 'C', 35, 'Receptive identification - rooms'),
  new ABLLSSkill('C36', 'C', 36, 'Receptive identification - outdoor items'),
  new ABLLSSkill('C37', 'C', 37, 'Receptive identification - vehicles'),
  new ABLLSSkill('C38', 'C', 38, 'Receptive identification - animals'),
  new ABLLSSkill('C39', 'C', 39, 'Receptive identification - people'),
  new ABLLSSkill('C40', 'C', 40, 'Receptive identification - actions'),
  new ABLLSSkill('C41', 'C', 41, 'Receptive identification - descriptive features'),
  new ABLLSSkill('C42', 'C', 42, 'Receptive identification - pronouns'),
  new ABLLSSkill('C43', 'C', 43, 'Receptive identification - prepositions'),
  new ABLLSSkill('C44', 'C', 44, 'Receptive identification - verbs'),
  new ABLLSSkill('C45', 'C', 45, 'Receptive identification - adjectives'),
  new ABLLSSkill('C46', 'C', 46, 'Receptive identification - adverbs'),
  new ABLLSSkill('C47', 'C', 47, 'Receptive identification - quantifiers'),
  new ABLLSSkill('C48', 'C', 48, 'Receptive identification - question words'),
  new ABLLSSkill('C49', 'C', 49, 'Receptive identification - categories'),
  new ABLLSSkill('C50', 'C', 50, 'Receptive identification - functions'),
  new ABLLSSkill('C51', 'C', 51, 'Receptive identification - attributes'),
  new ABLLSSkill('C52', 'C', 52, 'Receptive identification - abstract concepts'),
  new ABLLSSkill('C53', 'C', 53, 'Receptive matching - identical'),
  new ABLLSSkill('C54', 'C', 54, 'Receptive matching - different'),
  new ABLLSSkill('C55', 'C', 55, 'Receptive matching - categories'),
  new ABLLSSkill('C56', 'C', 56, 'Receptive matching - functions'),
  new ABLLSSkill('C57', 'C', 57, 'Receptive matching - attributes'),

  // Domain D: Imitation (D1-D44)
  new ABLLSSkill('D1', 'D', 1, 'Imitation gross motor - body parts'),
  new ABLLSSkill('D2', 'D', 2, 'Imitation gross motor - actions'),
  new ABLLSSkill('D3', 'D', 3, 'Imitation gross motor - locomotor'),
  new ABLLSSkill('D4', 'D', 4, 'Imitation gross motor - non-locomotor'),
  new ABLLSSkill('D5', 'D', 5, 'Imitation gross motor - manipulative'),
  new ABLLSSkill('D6', 'D', 6, 'Imitation gross motor - sequential'),
  new ABLLSSkill('D7', 'D', 7, 'Imitation gross motor - chained'),
  new ABLLSSkill('D8', 'D', 8, 'Imitation gross motor - novel'),
  new ABLLSSkill('D9', 'D', 9, 'Imitation fine motor - fingers'),
  new ABLLSSkill('D10', 'D', 10, 'Imitation fine motor - hands'),
  new ABLLSSkill('D11', 'D', 11, 'Imitation fine motor - arms'),
  new ABLLSSkill('D12', 'D', 12, 'Imitation fine motor - bilateral'),
  new ABLLSSkill('D13', 'D', 13, 'Imitation fine motor - unilateral'),
  new ABLLSSkill('D14', 'D', 14, 'Imitation fine motor - sequential'),
  new ABLLSSkill('D15', 'D', 15, 'Imitation fine motor - chained'),
  new ABLLSSkill('D16', 'D', 16, 'Imitation fine motor - novel'),
  new ABLLSSkill('D17', 'D', 17, 'Imitation oral motor - lips'),
  new ABLLSSkill('D18', 'D', 18, 'Imitation oral motor - tongue'),
  new ABLLSSkill('D19', 'D', 19, 'Imitation oral motor - jaw'),
  new ABLLSSkill('D20', 'D', 20, 'Imitation oral motor - breath'),
  new ABLLSSkill('D21', 'D', 21, 'Imitation oral motor - voice'),
  new ABLLSSkill('D22', 'D', 22, 'Imitation oral motor - speech'),
  new ABLLSSkill('D23', 'D', 23, 'Imitation vocal - single sounds'),
  new ABLLSSkill('D24', 'D', 24, 'Imitation vocal - syllables'),
  new ABLLSSkill('D25', 'D', 25, 'Imitation vocal - words'),
  new ABLLSSkill('D26', 'D', 26, 'Imitation vocal - phrases'),
  new ABLLSSkill('D27', 'D', 27, 'Imitation vocal - sentences'),
  new ABLLSSkill('D28', 'D', 28, 'Imitation vocal - songs'),
  new ABLLSSkill('D29', 'D', 29, 'Imitation vocal - novel'),
  new ABLLSSkill('D30', 'D', 30, 'Imitation actions with objects - single'),
  new ABLLSSkill('D31', 'D', 31, 'Imitation actions with objects - sequential'),
  new ABLLSSkill('D32', 'D', 32, 'Imitation actions with objects - chained'),
  new ABLLSSkill('D33', 'D', 33, 'Imitation actions with objects - novel'),
  new ABLLSSkill('D34', 'D', 34, 'Imitation drawing - lines'),
  new ABLLSSkill('D35', 'D', 35, 'Imitation drawing - shapes'),
  new ABLLSSkill('D36', 'D', 36, 'Imitation drawing - letters'),
  new ABLLSSkill('D37', 'D', 37, 'Imitation drawing - numbers'),
  new ABLLSSkill('D38', 'D', 38, 'Imitation drawing - pictures'),
  new ABLLSSkill('D39', 'D', 39, 'Imitation drawing - symbols'),
  new ABLLSSkill('D40', 'D', 40, 'Imitation drawing - novel'),
  new ABLLSSkill('D41', 'D', 41, 'Imitation play - single'),
  new ABLLSSkill('D42', 'D', 42, 'Imitation play - sequential'),
  new ABLLSSkill('D43', 'D', 43, 'Imitation play - chained'),
  new ABLLSSkill('D44', 'D', 44, 'Imitation play - novel'),

  // Domain E: Vocal Imitation (E1-E22)
  new ABLLSSkill('E1', 'E', 1, 'Vocal imitation - vowel sounds'),
  new ABLLSSkill('E2', 'E', 2, 'Vocal imitation - consonant sounds'),
  new ABLLSSkill('E3', 'E', 3, 'Vocal imitation - consonant-vowel combinations'),
  new ABLLSSkill('E4', 'E', 4, 'Vocal imitation - vowel-consonant combinations'),
  new ABLLSSkill('E5', 'E', 5, 'Vocal imitation - consonant-vowel-consonant combinations'),
  new ABLLSSkill('E6', 'E', 6, 'Vocal imitation - syllables'),
  new ABLLSSkill('E7', 'E', 7, 'Vocal imitation - words'),
  new ABLLSSkill('E8', 'E', 8, 'Vocal imitation - phrases'),
  new ABLLSSkill('E9', 'E', 9, 'Vocal imitation - sentences'),
  new ABLLSSkill('E10', 'E', 10, 'Vocal imitation - questions'),
  new ABLLSSkill('E11', 'E', 11, 'Vocal imitation - commands'),
  new ABLLSSkill('E12', 'E', 12, 'Vocal imitation - exclamations'),
  new ABLLSSkill('E13', 'E', 13, 'Vocal imitation - songs'),
  new ABLLSSkill('E14', 'E', 14, 'Vocal imitation - rhymes'),
  new ABLLSSkill('E15', 'E', 15, 'Vocal imitation - stories'),
  new ABLLSSkill('E16', 'E', 16, 'Vocal imitation - conversations'),
  new ABLLSSkill('E17', 'E', 17, 'Vocal imitation - spontaneous'),
  new ABLLSSkill('E18', 'E', 18, 'Vocal imitation - delayed'),
  new ABLLSSkill('E19', 'E', 19, 'Vocal imitation - generalized'),
  new ABLLSSkill('E20', 'E', 20, 'Vocal imitation - contextual'),
  new ABLLSSkill('E21', 'E', 21, 'Vocal imitation - functional'),
  new ABLLSSkill('E22', 'E', 22, 'Vocal imitation - novel'),

  // Domain F: Requests (F1-F25)
  new ABLLSSkill('F1', 'F', 1, 'Requests - body parts'),
  new ABLLSSkill('F2', 'F', 2, 'Requests - common objects'),
  new ABLLSSkill('F3', 'F', 3, 'Requests - foods'),
  new ABLLSSkill('F4', 'F', 4, 'Requests - clothing'),
  new ABLLSSkill('F5', 'F', 5, 'Requests - school items'),
  new ABLLSSkill('F6', 'F', 6, 'Requests - rooms'),
  new ABLLSSkill('F7', 'F', 7, 'Requests - outdoor items'),
  new ABLLSSkill('F8', 'F', 8, 'Requests - vehicles'),
  new ABLLSSkill('F9', 'F', 9, 'Requests - animals'),
  new ABLLSSkill('F10', 'F', 10, 'Requests - people'),
  new ABLLSSkill('F11', 'F', 11, 'Requests - actions'),
  new ABLLSSkill('F12', 'F', 12, 'Requests - descriptive features'),
  new ABLLSSkill('F13', 'F', 13, 'Requests - pronouns'),
  new ABLLSSkill('F14', 'F', 14, 'Requests - prepositions'),
  new ABLLSSkill('F15', 'F', 15, 'Requests - verbs'),
  new ABLLSSkill('F16', 'F', 16, 'Requests - adjectives'),
  new ABLLSSkill('F17', 'F', 17, 'Requests - adverbs'),
  new ABLLSSkill('F18', 'F', 18, 'Requests - quantifiers'),
  new ABLLSSkill('F19', 'F', 19, 'Requests - question words'),
  new ABLLSSkill('F20', 'F', 20, 'Requests - multiple items'),
  new ABLLSSkill('F21', 'F', 21, 'Requests - delayed gratification'),
  new ABLLSSkill('F22', 'F', 22, 'Requests - functionally equivalent responses'),
  new ABLLSSkill('F23', 'F', 23, 'Requests - spontaneous requests'),
  new ABLLSSkill('F24', 'F', 24, 'Requests - requesting information'),
  new ABLLSSkill('F25', 'F', 25, 'Requests - requesting assistance'),

  // Domain G: Labeling (G1-G57)
  new ABLLSSkill('G1', 'G', 1, 'Labeling - body parts'),
  new ABLLSSkill('G2', 'G', 2, 'Labeling - common objects'),
  new ABLLSSkill('G3', 'G', 3, 'Labeling - foods'),
  new ABLLSSkill('G4', 'G', 4, 'Labeling - clothing'),
  new ABLLSSkill('G5', 'G', 5, 'Labeling - school items'),
  new ABLLSSkill('G6', 'G', 6, 'Labeling - rooms'),
  new ABLLSSkill('G7', 'G', 7, 'Labeling - outdoor items'),
  new ABLLSSkill('G8', 'G', 8, 'Labeling - vehicles'),
  new ABLLSSkill('G9', 'G', 9, 'Labeling - animals'),
  new ABLLSSkill('G10', 'G', 10, 'Labeling - people'),
  new ABLLSSkill('G11', 'G', 11, 'Labeling - actions'),
  new ABLLSSkill('G12', 'G', 12, 'Labeling - descriptive features'),
  new ABLLSSkill('G13', 'G', 13, 'Labeling - pronouns'),
  new ABLLSSkill('G14', 'G', 14, 'Labeling - prepositions'),
  new ABLLSSkill('G15', 'G', 15, 'Labeling - verbs'),
  new ABLLSSkill('G16', 'G', 16, 'Labeling - adjectives'),
  new ABLLSSkill('G17', 'G', 17, 'Labeling - adverbs'),
  new ABLLSSkill('G18', 'G', 18, 'Labeling - quantifiers'),
  new ABLLSSkill('G19', 'G', 19, 'Labeling - question words'),
  new ABLLSSkill('G20', 'G', 20, 'Labeling - categories'),
  new ABLLSSkill('G21', 'G', 21, 'Labeling - functions'),
  new ABLLSSkill('G22', 'G', 22, 'Labeling - attributes'),
  new ABLLSSkill('G23', 'G', 23, 'Labeling - abstract concepts'),
  new ABLLSSkill('G24', 'G', 24, 'Labeling - environmental print'),
  new ABLLSSkill('G25', 'G', 25, 'Labeling - written words'),
  new ABLLSSkill('G26', 'G', 26, 'Labeling - symbols'),
  new ABLLSSkill('G27', 'G', 27, 'Labeling - pictures'),
  new ABLLSSkill('G28', 'G', 28, 'Labeling - photographs'),
  new ABLLSSkill('G29', 'G', 29, 'Labeling - gestures'),
  new ABLLSSkill('G30', 'G', 30, 'Labeling - signs'),
  new ABLLSSkill('G31', 'G', 31, 'Labeling - emotions'),
  new ABLLSSkill('G32', 'G', 32, 'Labeling - colors'),
  new ABLLSSkill('G33', 'G', 33, 'Labeling - shapes'),
  new ABLLSSkill('G34', 'G', 34, 'Labeling - sizes'),
  new ABLLSSkill('G35', 'G', 35, 'Labeling - textures'),
  new ABLLSSkill('G36', 'G', 36, 'Labeling - temperatures'),
  new ABLLSSkill('G37', 'G', 37, 'Labeling - tastes'),
  new ABLLSSkill('G38', 'G', 38, 'Labeling - smells'),
  new ABLLSSkill('G39', 'G', 39, 'Labeling - sounds'),
  new ABLLSSkill('G40', 'G', 40, 'Labeling - times'),
  new ABLLSSkill('G41', 'G', 41, 'Labeling - dates'),
  new ABLLSSkill('G42', 'G', 42, 'Labeling - numbers'),
  new ABLLSSkill('G43', 'G', 43, 'Labeling - letters'),
  new ABLLSSkill('G44', 'G', 44, 'Labeling - money'),
  new ABLLSSkill('G45', 'G', 45, 'Labeling - measurements'),
  new ABLLSSkill('G46', 'G', 46, 'Labeling - directions'),
  new ABLLSSkill('G47', 'G', 47, 'Labeling - positions'),
  new ABLLSSkill('G48', 'G', 48, 'Labeling - locations'),
  new ABLLSSkill('G49', 'G', 49, 'Labeling - distances'),
  new ABLLSSkill('G50', 'G', 50, 'Labeling - speeds'),
  new ABLLSSkill('G51', 'G', 51, 'Labeling - weights'),
  new ABLLSSkill('G52', 'G', 52, 'Labeling - volumes'),
  new ABLLSSkill('G53', 'G', 53, 'Labeling - areas'),
  new ABLLSSkill('G54', 'G', 54, 'Labeling - perimeters'),
  new ABLLSSkill('G55', 'G', 55, 'Labeling - angles'),
  new ABLLSSkill('G56', 'G', 56, 'Labeling - geometric figures'),
  new ABLLSSkill('G57', 'G', 57, 'Labeling - mathematical operations'),

  // Domain H: Intraverbals (H1-H25)
  new ABLLSSkill('H1', 'H', 1, 'Intraverbals - answers to questions'),
  new ABLLSSkill('H2', 'H', 2, 'Intraverbals - answers to wh-questions'),
  new ABLLSSkill('H3', 'H', 3, 'Intraverbals - answers to yes/no questions'),
  new ABLLSSkill('H4', 'H', 4, 'Intraverbals - answers to choice questions'),
  new ABLLSSkill('H5', 'H', 5, 'Intraverbals - answers to personal information questions'),
  new ABLLSSkill('H6', 'H', 6, 'Intraverbals - answers to academic questions'),
  new ABLLSSkill('H7', 'H', 7, 'Intraverbals - answers to social questions'),
  new ABLLSSkill('H8', 'H', 8, 'Intraverbals - answers to functional questions'),
  new ABLLSSkill('H9', 'H', 9, 'Intraverbals - answers to abstract questions'),
  new ABLLSSkill('H10', 'H', 10, 'Intraverbals - responses to statements'),
  new ABLLSSkill('H11', 'H', 11, 'Intraverbals - responses to commands'),
  new ABLLSSkill('H12', 'H', 12, 'Intraverbals - responses to requests'),
  new ABLLSSkill('H13', 'H', 13, 'Intraverbals - responses to comments'),
  new ABLLSSkill('H14', 'H', 14, 'Intraverbals - responses to jokes'),
  new ABLLSSkill('H15', 'H', 15, 'Intraverbals - responses to stories'),
  new ABLLSSkill('H16', 'H', 16, 'Intraverbals - responses to songs'),
  new ABLLSSkill('H17', 'H', 17, 'Intraverbals - responses to poems'),
  new ABLLSSkill('H18', 'H', 18, 'Intraverbals - responses to riddles'),
  new ABLLSSkill('H19', 'H', 19, 'Intraverbals - responses to idioms'),
  new ABLLSSkill('H20', 'H', 20, 'Intraverbals - responses to metaphors'),
  new ABLLSSkill('H21', 'H', 21, 'Intraverbals - responses to similes'),
  new ABLLSSkill('H22', 'H', 22, 'Intraverbals - responses to proverbs'),
  new ABLLSSkill('H23', 'H', 23, 'Intraverbals - responses to abstract concepts'),
  new ABLLSSkill('H24', 'H', 24, 'Intraverbals - responses to hypothetical situations'),
  new ABLLSSkill('H25', 'H', 25, 'Intraverbals - responses to novel situations'),

  // Domain I: Spontaneous Vocalizations (I1-I25)
  new ABLLSSkill('I1', 'I', 1, 'Spontaneous vocalizations - vowel sounds'),
  new ABLLSSkill('I2', 'I', 2, 'Spontaneous vocalizations - consonant sounds'),
  new ABLLSSkill('I3', 'I', 3, 'Spontaneous vocalizations - syllables'),
  new ABLLSSkill('I4', 'I', 4, 'Spontaneous vocalizations - words'),
  new ABLLSSkill('I5', 'I', 5, 'Spontaneous vocalizations - phrases'),
  new ABLLSSkill('I6', 'I', 6, 'Spontaneous vocalizations - sentences'),
  new ABLLSSkill('I7', 'I', 7, 'Spontaneous vocalizations - questions'),
  new ABLLSSkill('I8', 'I', 8, 'Spontaneous vocalizations - commands'),
  new ABLLSSkill('I9', 'I', 9, 'Spontaneous vocalizations - exclamations'),
  new ABLLSSkill('I10', 'I', 10, 'Spontaneous vocalizations - songs'),
  new ABLLSSkill('I11', 'I', 11, 'Spontaneous vocalizations - rhymes'),
  new ABLLSSkill('I12', 'I', 12, 'Spontaneous vocalizations - stories'),
  new ABLLSSkill('I13', 'I', 13, 'Spontaneous vocalizations - conversations'),
  new ABLLSSkill('I14', 'I', 14, 'Spontaneous vocalizations - comments'),
  new ABLLSSkill('I15', 'I', 15, 'Spontaneous vocalizations - observations'),
  new ABLLSSkill('I16', 'I', 16, 'Spontaneous vocalizations - requests'),
  new ABLLSSkill('I17', 'I', 17, 'Spontaneous vocalizations - protests'),
  new ABLLSSkill('I18', 'I', 18, 'Spontaneous vocalizations - greetings'),
  new ABLLSSkill('I19', 'I', 19, 'Spontaneous vocalizations - farewells'),
  new ABLLSSkill('I20', 'I', 20, 'Spontaneous vocalizations - expressions of emotion'),
  new ABLLSSkill('I21', 'I', 21, 'Spontaneous vocalizations - expressions of need'),
  new ABLLSSkill('I22', 'I', 22, 'Spontaneous vocalizations - expressions of preference'),
  new ABLLSSkill('I23', 'I', 23, 'Spontaneous vocalizations - expressions of opinion'),
  new ABLLSSkill('I24', 'I', 24, 'Spontaneous vocalizations - expressions of intention'),
  new ABLLSSkill('I25', 'I', 25, 'Spontaneous vocalizations - novel expressions'),

  // Domain J: Syntax & Grammar (J1-J25)
  new ABLLSSkill('J1', 'J', 1, 'Syntax & grammar - noun-verb combinations'),
  new ABLLSSkill('J2', 'J', 2, 'Syntax & grammar - adjective-noun combinations'),
  new ABLLSSkill('J3', 'J', 3, 'Syntax & grammar - verb-adverb combinations'),
  new ABLLSSkill('J4', 'J', 4, 'Syntax & grammar - prepositional phrases'),
  new ABLLSSkill('J5', 'J', 5, 'Syntax & grammar - possessive constructions'),
  new ABLLSSkill('J6', 'J', 6, 'Syntax & grammar - plural forms'),
  new ABLLSSkill('J7', 'J', 7, 'Syntax & grammar - past tense forms'),
  new ABLLSSkill('J8', 'J', 8, 'Syntax & grammar - present tense forms'),
  new ABLLSSkill('J9', 'J', 9, 'Syntax & grammar - future tense forms'),
  new ABLLSSkill('J10', 'J', 10, 'Syntax & grammar - progressive forms'),
  new ABLLSSkill('J11', 'J', 11, 'Syntax & grammar - perfect forms'),
  new ABLLSSkill('J12', 'J', 12, 'Syntax & grammar - conditional forms'),
  new ABLLSSkill('J13', 'J', 13, 'Syntax & grammar - passive voice'),
  new ABLLSSkill('J14', 'J', 14, 'Syntax & grammar - active voice'),
  new ABLLSSkill('J15', 'J', 15, 'Syntax & grammar - interrogative forms'),
  new ABLLSSkill('J16', 'J', 16, 'Syntax & grammar - negative forms'),
  new ABLLSSkill('J17', 'J', 17, 'Syntax & grammar - compound sentences'),
  new ABLLSSkill('J18', 'J', 18, 'Syntax & grammar - complex sentences'),
  new ABLLSSkill('J19', 'J', 19, 'Syntax & grammar - embedded clauses'),
  new ABLLSSkill('J20', 'J', 20, 'Syntax & grammar - relative clauses'),
  new ABLLSSkill('J21', 'J', 21, 'Syntax & grammar - infinitive phrases'),
  new ABLLSSkill('J22', 'J', 22, 'Syntax & grammar - gerund phrases'),
  new ABLLSSkill('J23', 'J', 23, 'Syntax & grammar - participial phrases'),
  new ABLLSSkill('J24', 'J', 24, 'Syntax & grammar - appositive phrases'),
  new ABLLSSkill('J25', 'J', 25, 'Syntax & grammar - elliptical constructions'),

  // Domain K: Reading (K1-K25)
  new ABLLSSkill('K1', 'K', 1, 'Reading - letter recognition'),
  new ABLLSSkill('K2', 'K', 2, 'Reading - letter sounds'),
  new ABLLSSkill('K3', 'K', 3, 'Reading - consonant blends'),
  new ABLLSSkill('K4', 'K', 4, 'Reading - digraphs'),
  new ABLLSSkill('K5', 'K', 5, 'Reading - vowel combinations'),
  new ABLLSSkill('K6', 'K', 6, 'Reading - syllable division'),
  new ABLLSSkill('K7', 'K', 7, 'Reading - phonetic decoding'),
  new ABLLSSkill('K8', 'K', 8, 'Reading - sight words'),
  new ABLLSSkill('K9', 'K', 9, 'Reading - high frequency words'),
  new ABLLSSkill('K10', 'K', 10, 'Reading - irregular words'),
  new ABLLSSkill('K11', 'K', 11, 'Reading - word families'),
  new ABLLSSkill('K12', 'K', 12, 'Reading - compound words'),
  new ABLLSSkill('K13', 'K', 13, 'Reading - contractions'),
  new ABLLSSkill('K14', 'K', 14, 'Reading - abbreviations'),
  new ABLLSSkill('K15', 'K', 15, 'Reading - acronyms'),
  new ABLLSSkill('K16', 'K', 16, 'Reading - prefixes'),
  new ABLLSSkill('K17', 'K', 17, 'Reading - suffixes'),
  new ABLLSSkill('K18', 'K', 18, 'Reading - roots'),
  new ABLLSSkill('K19', 'K', 19, 'Reading - affixes'),
  new ABLLSSkill('K20', 'K', 20, 'Reading - word structure'),
  new ABLLSSkill('K21', 'K', 21, 'Reading - sentence structure'),
  new ABLLSSkill('K22', 'K', 22, 'Reading - paragraph structure'),
  new ABLLSSkill('K23', 'K', 23, 'Reading - text structure'),
  new ABLLSSkill('K24', 'K', 24, 'Reading - literary devices'),
  new ABLLSSkill('K25', 'K', 25, 'Reading - literary genres'),

  // Domain L: Math (L1-L25)
  new ABLLSSkill('L1', 'L', 1, 'Math - number recognition'),
  new ABLLSSkill('L2', 'L', 2, 'Math - number writing'),
  new ABLLSSkill('L3', 'L', 3, 'Math - counting'),
  new ABLLSSkill('L4', 'L', 4, 'Math - one-to-one correspondence'),
  new ABLLSSkill('L5', 'L', 5, 'Math - cardinality'),
  new ABLLSSkill('L6', 'L', 6, 'Math - ordinal numbers'),
  new ABLLSSkill('L7', 'L', 7, 'Math - number sequence'),
  new ABLLSSkill('L8', 'L', 8, 'Math - number patterns'),
  new ABLLSSkill('L9', 'L', 9, 'Math - addition'),
  new ABLLSSkill('L10', 'L', 10, 'Math - subtraction'),
  new ABLLSSkill('L11', 'L', 11, 'Math - multiplication'),
  new ABLLSSkill('L12', 'L', 12, 'Math - division'),
  new ABLLSSkill('L13', 'L', 13, 'Math - fractions'),
  new ABLLSSkill('L14', 'L', 14, 'Math - decimals'),
  new ABLLSSkill('L15', 'L', 15, 'Math - percentages'),
  new ABLLSSkill('L16', 'L', 16, 'Math - ratios'),
  new ABLLSSkill('L17', 'L', 17, 'Math - proportions'),
  new ABLLSSkill('L18', 'L', 18, 'Math - algebraic expressions'),
  new ABLLSSkill('L19', 'L', 19, 'Math - equations'),
  new ABLLSSkill('L20', 'L', 20, 'Math - inequalities'),
  new ABLLSSkill('L21', 'L', 21, 'Math - geometry'),
  new ABLLSSkill('L22', 'L', 22, 'Math - measurement'),
  new ABLLSSkill('L23', 'L', 23, 'Math - data analysis'),
  new ABLLSSkill('L24', 'L', 24, 'Math - probability'),
  new ABLLSSkill('L25', 'L', 25, 'Math - statistics'),

  // Domain M: Writing (M1-M25)
  new ABLLSSkill('M1', 'M', 1, 'Writing - letter formation'),
  new ABLLSSkill('M2', 'M', 2, 'Writing - letter spacing'),
  new ABLLSSkill('M3', 'M', 3, 'Writing - letter alignment'),
  new ABLLSSkill('M4', 'M', 4, 'Writing - letter size'),
  new ABLLSSkill('M5', 'M', 5, 'Writing - letter legibility'),
  new ABLLSSkill('M6', 'M', 6, 'Writing - word formation'),
  new ABLLSSkill('M7', 'M', 7, 'Writing - word spacing'),
  new ABLLSSkill('M8', 'M', 8, 'Writing - word alignment'),
  new ABLLSSkill('M9', 'M', 9, 'Writing - word size'),
  new ABLLSSkill('M10', 'M', 10, 'Writing - word legibility'),
  new ABLLSSkill('M11', 'M', 11, 'Writing - sentence formation'),
  new ABLLSSkill('M12', 'M', 12, 'Writing - sentence punctuation'),
  new ABLLSSkill('M13', 'M', 13, 'Writing - sentence capitalization'),
  new ABLLSSkill('M14', 'M', 14, 'Writing - sentence structure'),
  new ABLLSSkill('M15', 'M', 15, 'Writing - sentence clarity'),
  new ABLLSSkill('M16', 'M', 16, 'Writing - paragraph formation'),
  new ABLLSSkill('M17', 'M', 17, 'Writing - paragraph organization'),
  new ABLLSSkill('M18', 'M', 18, 'Writing - paragraph coherence'),
  new ABLLSSkill('M19', 'M', 19, 'Writing - paragraph unity'),
  new ABLLSSkill('M20', 'M', 20, 'Writing - paragraph development'),
  new ABLLSSkill('M21', 'M', 21, 'Writing - essay formation'),
  new ABLLSSkill('M22', 'M', 22, 'Writing - essay organization'),
  new ABLLSSkill('M23', 'M', 23, 'Writing - essay coherence'),
  new ABLLSSkill('M24', 'M', 24, 'Writing - essay unity'),
  new ABLLSSkill('M25', 'M', 25, 'Writing - essay development'),

  // Domain N: Spelling (N1-N25)
  new ABLLSSkill('N1', 'N', 1, 'Spelling - letter recognition'),
  new ABLLSSkill('N2', 'N', 2, 'Spelling - letter sequencing'),
  new ABLLSSkill('N3', 'N', 3, 'Spelling - phonetic spelling'),
  new ABLLSSkill('N4', 'N', 4, 'Spelling - sight words'),
  new ABLLSSkill('N5', 'N', 5, 'Spelling - high frequency words'),
  new ABLLSSkill('N6', 'N', 6, 'Spelling - irregular words'),
  new ABLLSSkill('N7', 'N', 7, 'Spelling - word families'),
  new ABLLSSkill('N8', 'N', 8, 'Spelling - compound words'),
  new ABLLSSkill('N9', 'N', 9, 'Spelling - contractions'),
  new ABLLSSkill('N10', 'N', 10, 'Spelling - abbreviations'),
  new ABLLSSkill('N11', 'N', 11, 'Spelling - acronyms'),
  new ABLLSSkill('N12', 'N', 12, 'Spelling - prefixes'),
  new ABLLSSkill('N13', 'N', 13, 'Spelling - suffixes'),
  new ABLLSSkill('N14', 'N', 14, 'Spelling - roots'),
  new ABLLSSkill('N15', 'N', 15, 'Spelling - affixes'),
  new ABLLSSkill('N16', 'N', 16, 'Spelling - word structure'),
  new ABLLSSkill('N17', 'N', 17, 'Spelling - syllable division'),
  new ABLLSSkill('N18', 'N', 18, 'Spelling - vowel combinations'),
  new ABLLSSkill('N19', 'N', 19, 'Spelling - consonant blends'),
  new ABLLSSkill('N20', 'N', 20, 'Spelling - digraphs'),
  new ABLLSSkill('N21', 'N', 21, 'Spelling - diphthongs'),
  new ABLLSSkill('N22', 'N', 22, 'Spelling - silent letters'),
  new ABLLSSkill('N23', 'N', 23, 'Spelling - homophones'),
  new ABLLSSkill('N24', 'N', 24, 'Spelling - homographs'),
  new ABLLSSkill('N25', 'N', 25, 'Spelling - heteronyms'),

  // Domain O: Play & Leisure Skills (O1-O25)
  new ABLLSSkill('O1', 'O', 1, 'Play & leisure skills - solitary play'),
  new ABLLSSkill('O2', 'O', 2, 'Play & leisure skills - parallel play'),
  new ABLLSSkill('O3', 'O', 3, 'Play & leisure skills - associative play'),
  new ABLLSSkill('O4', 'O', 4, 'Play & leisure skills - cooperative play'),
  new ABLLSSkill('O5', 'O', 5, 'Play & leisure skills - symbolic play'),
  new ABLLSSkill('O6', 'O', 6, 'Play & leisure skills - constructive play'),
  new ABLLSSkill('O7', 'O', 7, 'Play & leisure skills - creative play'),
  new ABLLSSkill('O8', 'O', 8, 'Play & leisure skills - dramatic play'),
  new ABLLSSkill('O9', 'O', 9, 'Play & leisure skills - games with rules'),
  new ABLLSSkill('O10', 'O', 10, 'Play & leisure skills - sports'),
  new ABLLSSkill('O11', 'O', 11, 'Play & leisure skills - hobbies'),
  new ABLLSSkill('O12', 'O', 12, 'Play & leisure skills - arts and crafts'),
  new ABLLSSkill('O13', 'O', 13, 'Play & leisure skills - music'),
  new ABLLSSkill('O14', 'O', 14, 'Play & leisure skills - dance'),
  new ABLLSSkill('O15', 'O', 15, 'Play & leisure skills - drama'),
  new ABLLSSkill('O16', 'O', 16, 'Play & leisure skills - reading for pleasure'),
  new ABLLSSkill('O17', 'O', 17, 'Play & leisure skills - writing for pleasure'),
  new ABLLSSkill('O18', 'O', 18, 'Play & leisure skills - mathematics for pleasure'),
  new ABLLSSkill('O19', 'O', 19, 'Play & leisure skills - science for pleasure'),
  new ABLLSSkill('O20', 'O', 20, 'Play & leisure skills - social activities'),
  new ABLLSSkill('O21', 'O', 21, 'Play & leisure skills - community activities'),
  new ABLLSSkill('O22', 'O', 22, 'Play & leisure skills - cultural activities'),
  new ABLLSSkill('O23', 'O', 23, 'Play & leisure skills - recreational activities'),
  new ABLLSSkill('O24', 'O', 24, 'Play & leisure skills - outdoor activities'),
  new ABLLSSkill('O25', 'O', 25, 'Play & leisure skills - indoor activities'),

  // Domain P: Social Interaction Skills (P1-P28)
  new ABLLSSkill('P1', 'P', 1, 'Social interaction skills - greeting'),
  new ABLLSSkill('P2', 'P', 2, 'Social interaction skills - introduction'),
  new ABLLSSkill('P3', 'P', 3, 'Social interaction skills - eye contact'),
  new ABLLSSkill('P4', 'P', 4, 'Social interaction skills - facial expressions'),
  new ABLLSSkill('P5', 'P', 5, 'Social interaction skills - gestures'),
  new ABLLSSkill('P6', 'P', 6, 'Social interaction skills - body language'),
  new ABLLSSkill('P7', 'P', 7, 'Social interaction skills - personal space'),
  new ABLLSSkill('P8', 'P', 8, 'Social interaction skills - turn-taking'),
  new ABLLSSkill('P9', 'P', 9, 'Social interaction skills - sharing'),
  new ABLLSSkill('P10', 'P', 10, 'Social interaction skills - cooperation'),
  new ABLLSSkill('P11', 'P', 11, 'Social interaction skills - compromise'),
  new ABLLSSkill('P12', 'P', 12, 'Social interaction skills - negotiation'),
  new ABLLSSkill('P13', 'P', 13, 'Social interaction skills - conflict resolution'),
  new ABLLSSkill('P14', 'P', 14, 'Social interaction skills - empathy'),
  new ABLLSSkill('P15', 'P', 15, 'Social interaction skills - sympathy'),
  new ABLLSSkill('P16', 'P', 16, 'Social interaction skills - perspective-taking'),
  new ABLLSSkill('P17', 'P', 17, 'Social interaction skills - emotional regulation'),
  new ABLLSSkill('P18', 'P', 18, 'Social interaction skills - self-control'),
  new ABLLSSkill('P19', 'P', 19, 'Social interaction skills - impulse control'),
  new ABLLSSkill('P20', 'P', 20, 'Social interaction skills - patience'),
  new ABLLSSkill('P21', 'P', 21, 'Social interaction skills - tolerance'),
  new ABLLSSkill('P22', 'P', 22, 'Social interaction skills - respect'),
  new ABLLSSkill('P23', 'P', 23, 'Social interaction skills - politeness'),
  new ABLLSSkill('P24', 'P', 24, 'Social interaction skills - courtesy'),
  new ABLLSSkill('P25', 'P', 25, 'Social interaction skills - gratitude'),
  new ABLLSSkill('P26', 'P', 26, 'Social interaction skills - forgiveness'),
  new ABLLSSkill('P27', 'P', 27, 'Social interaction skills - loyalty'),
  new ABLLSSkill('P28', 'P', 28, 'Social interaction skills - trustworthiness'),

  // Domain Q: Group Skills (Q1-Q25)
  new ABLLSSkill('Q1', 'Q', 1, 'Group skills - following group instructions'),
  new ABLLSSkill('Q2', 'Q', 2, 'Group skills - participating in group activities'),
  new ABLLSSkill('Q3', 'Q', 3, 'Group skills - contributing to group discussions'),
  new ABLLSSkill('Q4', 'Q', 4, 'Group skills - respecting group decisions'),
  new ABLLSSkill('Q5', 'Q', 5, 'Group skills - supporting group members'),
  new ABLLSSkill('Q6', 'Q', 6, 'Group skills - leading group activities'),
  new ABLLSSkill('Q7', 'Q', 7, 'Group skills - organizing group activities'),
  new ABLLSSkill('Q8', 'Q', 8, 'Group skills - facilitating group discussions'),
  new ABLLSSkill('Q9', 'Q', 9, 'Group skills - mediating group conflicts'),
  new ABLLSSkill('Q10', 'Q', 10, 'Group skills - representing the group'),
  new ABLLSSkill('Q11', 'Q', 11, 'Group skills - advocating for the group'),
  new ABLLSSkill('Q12', 'Q', 12, 'Group skills - defending the group'),
  new ABLLSSkill('Q13', 'Q', 13, 'Group skills - promoting group cohesion'),
  new ABLLSSkill('Q14', 'Q', 14, 'Group skills - maintaining group morale'),
  new ABLLSSkill('Q15', 'Q', 15, 'Group skills - enhancing group performance'),
  new ABLLSSkill('Q16', 'Q', 16, 'Group skills - evaluating group outcomes'),
  new ABLLSSkill('Q17', 'Q', 17, 'Group skills - planning group activities'),
  new ABLLSSkill('Q18', 'Q', 18, 'Group skills - implementing group plans'),
  new ABLLSSkill('Q19', 'Q', 19, 'Group skills - monitoring group progress'),
  new ABLLSSkill('Q20', 'Q', 20, 'Group skills - adjusting group strategies'),
  new ABLLSSkill('Q21', 'Q', 21, 'Group skills - celebrating group achievements'),
  new ABLLSSkill('Q22', 'Q', 22, 'Group skills - learning from group experiences'),
  new ABLLSSkill('Q23', 'Q', 23, 'Group skills - applying group lessons'),
  new ABLLSSkill('Q24', 'Q', 24, 'Group skills - transferring group skills'),
  new ABLLSSkill('Q25', 'Q', 25, 'Group skills - generalizing group skills'),

  // Domain R: Classroom Skills (R1-R25)
  new ABLLSSkill('R1', 'R', 1, 'Classroom skills - sitting appropriately'),
  new ABLLSSkill('R2', 'R', 2, 'Classroom skills - attending to instruction'),
  new ABLLSSkill('R3', 'R', 3, 'Classroom skills - following classroom rules'),
  new ABLLSSkill('R4', 'R', 4, 'Classroom skills - participating in class activities'),
  new ABLLSSkill('R5', 'R', 5, 'Classroom skills - completing class assignments'),
  new ABLLSSkill('R6', 'R', 6, 'Classroom skills - turning in assignments'),
  new ABLLSSkill('R7', 'R', 7, 'Classroom skills - organizing materials'),
  new ABLLSSkill('R8', 'R', 8, 'Classroom skills - managing time'),
  new ABLLSSkill('R9', 'R', 9, 'Classroom skills - studying'),
  new ABLLSSkill('R10', 'R', 10, 'Classroom skills - note-taking'),
  new ABLLSSkill('R11', 'R', 11, 'Classroom skills - test-taking'),
  new ABLLSSkill('R12', 'R', 12, 'Classroom skills - asking questions'),
  new ABLLSSkill('R13', 'R', 13, 'Classroom skills - answering questions'),
  new ABLLSSkill('R14', 'R', 14, 'Classroom skills - volunteering'),
  new ABLLSSkill('R15', 'R', 15, 'Classroom skills - waiting for turns'),
  new ABLLSSkill('R16', 'R', 16, 'Classroom skills - raising hands'),
  new ABLLSSkill('R17', 'R', 17, 'Classroom skills - staying on task'),
  new ABLLSSkill('R18', 'R', 18, 'Classroom skills - completing work independently'),
  new ABLLSSkill('R19', 'R', 19, 'Classroom skills - seeking help appropriately'),
  new ABLLSSkill('R20', 'R', 20, 'Classroom skills - accepting feedback'),
  new ABLLSSkill('R21', 'R', 21, 'Classroom skills - revising work'),
  new ABLLSSkill('R22', 'R', 22, 'Classroom skills - improving work'),
  new ABLLSSkill('R23', 'R', 23, 'Classroom skills - reflecting on work'),
  new ABLLSSkill('R24', 'R', 24, 'Classroom skills - setting academic goals'),
  new ABLLSSkill('R25', 'R', 25, 'Classroom skills - achieving academic goals'),

  // Domain S: Early Academic Skills (S1-S25)
  new ABLLSSkill('S1', 'S', 1, 'Early academic skills - recognizing letters'),
  new ABLLSSkill('S2', 'S', 2, 'Early academic skills - recognizing numbers'),
  new ABLLSSkill('S3', 'S', 3, 'Early academic skills - recognizing shapes'),
  new ABLLSSkill('S4', 'S', 4, 'Early academic skills - recognizing colors'),
  new ABLLSSkill('S5', 'S', 5, 'Early academic skills - recognizing patterns'),
  new ABLLSSkill('S6', 'S', 6, 'Early academic skills - recognizing sequences'),
  new ABLLSSkill('S7', 'S', 7, 'Early academic skills - recognizing categories'),
  new ABLLSSkill('S8', 'S', 8, 'Early academic skills - recognizing attributes'),
  new ABLLSSkill('S9', 'S', 9, 'Early academic skills - recognizing functions'),
  new ABLLSSkill('S10', 'S', 10, 'Early academic skills - recognizing positions'),
  new ABLLSSkill('S11', 'S', 11, 'Early academic skills - recognizing directions'),
  new ABLLSSkill('S12', 'S', 12, 'Early academic skills - recognizing sizes'),
  new ABLLSSkill('S13', 'S', 13, 'Early academic skills - recognizing quantities'),
  new ABLLSSkill('S14', 'S', 14, 'Early academic skills - recognizing weights'),
  new ABLLSSkill('S15', 'S', 15, 'Early academic skills - recognizing temperatures'),
  new ABLLSSkill('S16', 'S', 16, 'Early academic skills - recognizing textures'),
  new ABLLSSkill('S17', 'S', 17, 'Early academic skills - recognizing tastes'),
  new ABLLSSkill('S18', 'S', 18, 'Early academic skills - recognizing smells'),
  new ABLLSSkill('S19', 'S', 19, 'Early academic skills - recognizing sounds'),
  new ABLLSSkill('S20', 'S', 20, 'Early academic skills - recognizing time concepts'),
  new ABLLSSkill('S21', 'S', 21, 'Early academic skills - recognizing money'),
  new ABLLSSkill('S22', 'S', 22, 'Early academic skills - recognizing measurements'),
  new ABLLSSkill('S23', 'S', 23, 'Early academic skills - recognizing spatial relationships'),
  new ABLLSSkill('S24', 'S', 24, 'Early academic skills - recognizing temporal relationships'),
  new ABLLSSkill('S25', 'S', 25, 'Early academic skills - recognizing cause and effect'),

  // Domain T: Life Skills (T1-T25)
  new ABLLSSkill('T1', 'T', 1, 'Life skills - personal hygiene'),
  new ABLLSSkill('T2', 'T', 2, 'Life skills - dressing'),
  new ABLLSSkill('T3', 'T', 3, 'Life skills - eating'),
  new ABLLSSkill('T4', 'T', 4, 'Life skills - grooming'),
  new ABLLSSkill('T5', 'T', 5, 'Life skills - toileting'),
  new ABLLSSkill('T6', 'T', 6, 'Life skills - sleeping'),
  new ABLLSSkill('T7', 'T', 7, 'Life skills - exercise'),
  new ABLLSSkill('T8', 'T', 8, 'Life skills - safety'),
  new ABLLSSkill('T9', 'T', 9, 'Life skills - health'),
  new ABLLSSkill('T10', 'T', 10, 'Life skills - nutrition'),
  new ABLLSSkill('T11', 'T', 11, 'Life skills - transportation'),
  new ABLLSSkill('T12', 'T', 12, 'Life skills - shopping'),
  new ABLLSSkill('T13', 'T', 13, 'Life skills - cooking'),
  new ABLLSSkill('T14', 'T', 14, 'Life skills - cleaning'),
  new ABLLSSkill('T15', 'T', 15, 'Life skills - home maintenance'),
  new ABLLSSkill('T16', 'T', 16, 'Life skills - money management'),
  new ABLLSSkill('T17', 'T', 17, 'Life skills - time management'),
  new ABLLSSkill('T18', 'T', 18, 'Life skills - communication'),
  new ABLLSSkill('T19', 'T', 19, 'Life skills - social skills'),
  new ABLLSSkill('T20', 'T', 20, 'Life skills - community participation'),
  new ABLLSSkill('T21', 'T', 21, 'Life skills - recreation'),
  new ABLLSSkill('T22', 'T', 22, 'Life skills - employment'),
  new ABLLSSkill('T23', 'T', 23, 'Life skills - relationships'),
  new ABLLSSkill('T24', 'T', 24, 'Life skills - decision-making'),
  new ABLLSSkill('T25', 'T', 25, 'Life skills - problem-solving'),

  // Domain U: Independent Functioning (U1-U25)
  new ABLLSSkill('U1', 'U', 1, 'Independent functioning - self-feeding'),
  new ABLLSSkill('U2', 'U', 2, 'Independent functioning - self-dressing'),
  new ABLLSSkill('U3', 'U', 3, 'Independent functioning - self-grooming'),
  new ABLLSSkill('U4', 'U', 4, 'Independent functioning - self-toileting'),
  new ABLLSSkill('U5', 'U', 5, 'Independent functioning - self-medication'),
  new ABLLSSkill('U6', 'U', 6, 'Independent functioning - self-exercise'),
  new ABLLSSkill('U7', 'U', 7, 'Independent functioning - self-sleeping'),
  new ABLLSSkill('U8', 'U', 8, 'Independent functioning - self-safety'),
  new ABLLSSkill('U9', 'U', 9, 'Independent functioning - self-health'),
  new ABLLSSkill('U10', 'U', 10, 'Independent functioning - self-navigation'),
  new ABLLSSkill('U11', 'U', 11, 'Independent functioning - self-shopping'),
  new ABLLSSkill('U12', 'U', 12, 'Independent functioning - self-cooking'),
  new ABLLSSkill('U13', 'U', 13, 'Independent functioning - self-cleaning'),
  new ABLLSSkill('U14', 'U', 14, 'Independent functioning - self-maintenance'),
  new ABLLSSkill('U15', 'U', 15, 'Independent functioning - self-finances'),
  new ABLLSSkill('U16', 'U', 16, 'Independent functioning - self-scheduling'),
  new ABLLSSkill('U17', 'U', 17, 'Independent functioning - self-communication'),
  new ABLLSSkill('U18', 'U', 18, 'Independent functioning - self-socializing'),
  new ABLLSSkill('U19', 'U', 19, 'Independent functioning - self-community participation'),
  new ABLLSSkill('U20', 'U', 20, 'Independent functioning - self-recreation'),
  new ABLLSSkill('U21', 'U', 21, 'Independent functioning - self-employment'),
  new ABLLSSkill('U22', 'U', 22, 'Independent functioning - self-relationships'),
  new ABLLSSkill('U23', 'U', 23, 'Independent functioning - self-decision making'),
  new ABLLSSkill('U24', 'U', 24, 'Independent functioning - self-problem solving'),
  new ABLLSSkill('U25', 'U', 25, 'Independent functioning - self-advocacy'),

  // Domain V: Community Access (V1-V25)
  new ABLLSSkill('V1', 'V', 1, 'Community access - neighborhood navigation'),
  new ABLLSSkill('V2', 'V', 2, 'Community access - public transportation'),
  new ABLLSSkill('V3', 'V', 3, 'Community access - store shopping'),
  new ABLLSSkill('V4', 'V', 4, 'Community access - restaurant dining'),
  new ABLLSSkill('V5', 'V', 5, 'Community access - library use'),
  new ABLLSSkill('V6', 'V', 6, 'Community access - bank transactions'),
  new ABLLSSkill('V7', 'V', 7, 'Community access - post office services'),
  new ABLLSSkill('V8', 'V', 8, 'Community access - medical appointments'),
  new ABLLSSkill('V9', 'V', 9, 'Community access - recreational facilities'),
  new ABLLSSkill('V10', 'V', 10, 'Community access - entertainment venues'),
  new ABLLSSkill('V11', 'V', 11, 'Community access - religious services'),
  new ABLLSSkill('V12', 'V', 12, 'Community access - government services'),
  new ABLLSSkill('V13', 'V', 13, 'Community access - emergency services'),
  new ABLLSSkill('V14', 'V', 14, 'Community access - volunteer opportunities'),
  new ABLLSSkill('V15', 'V', 15, 'Community access - employment services'),
  new ABLLSSkill('V16', 'V', 16, 'Community access - educational services'),
  new ABLLSSkill('V17', 'V', 17, 'Community access - social services'),
  new ABLLSSkill('V18', 'V', 18, 'Community access - legal services'),
  new ABLLSSkill('V19', 'V', 19, 'Community access - advocacy services'),
  new ABLLSSkill('V20', 'V', 20, 'Community access - support groups'),
  new ABLLSSkill('V21', 'V', 21, 'Community access - clubs and organizations'),
  new ABLLSSkill('V22', 'V', 22, 'Community access - sports and fitness'),
  new ABLLSSkill('V23', 'V', 23, 'Community access - cultural events'),
  new ABLLSSkill('V24', 'V', 24, 'Community access - travel'),
  new ABLLSSkill('V25', 'V', 25, 'Community access - digital access'),

  // Domain W: Vocational Skills (W1-W25)
  new ABLLSSkill('W1', 'W', 1, 'Vocational skills - job awareness'),
  new ABLLSSkill('W2', 'W', 2, 'Vocational skills - career exploration'),
  new ABLLSSkill('W3', 'W', 3, 'Vocational skills - job search'),
  new ABLLSSkill('W4', 'W', 4, 'Vocational skills - resume writing'),
  new ABLLSSkill('W5', 'W', 5, 'Vocational skills - interview skills'),
  new ABLLSSkill('W6', 'W', 6, 'Vocational skills - job application'),
  new ABLLSSkill('W7', 'W', 7, 'Vocational skills - job acceptance'),
  new ABLLSSkill('W8', 'W', 8, 'Vocational skills - job orientation'),
  new ABLLSSkill('W9', 'W', 9, 'Vocational skills - job training'),
  new ABLLSSkill('W10', 'W', 10, 'Vocational skills - job performance'),
  new ABLLSSkill('W11', 'W', 11, 'Vocational skills - job safety'),
  new ABLLSSkill('W12', 'W', 12, 'Vocational skills - job communication'),
  new ABLLSSkill('W13', 'W', 13, 'Vocational skills - job relationships'),
  new ABLLSSkill('W14', 'W', 14, 'Vocational skills - job problem-solving'),
  new ABLLSSkill('W15', 'W', 15, 'Vocational skills - job adaptation'),
  new ABLLSSkill('W16', 'W', 16, 'Vocational skills - job advancement'),
  new ABLLSSkill('W17', 'W', 17, 'Vocational skills - job retention'),
  new ABLLSSkill('W18', 'W', 18, 'Vocational skills - job termination'),
  new ABLLSSkill('W19', 'W', 19, 'Vocational skills - job transition'),
  new ABLLSSkill('W20', 'W', 20, 'Vocational skills - entrepreneurship'),
  new ABLLSSkill('W21', 'W', 21, 'Vocational skills - self-employment'),
  new ABLLSSkill('W22', 'W', 22, 'Vocational skills - volunteer work'),
  new ABLLSSkill('W23', 'W', 23, 'Vocational skills - internships'),
  new ABLLSSkill('W24', 'W', 24, 'Vocational skills - apprenticeships'),
  new ABLLSSkill('W25', 'W', 25, 'Vocational skills - career development'),

  // Domain X: Self-Help Skills (X1-X25)
  new ABLLSSkill('X1', 'X', 1, 'Self-help skills - dressing'),
  new ABLLSSkill('X2', 'X', 2, 'Self-help skills - grooming'),
  new ABLLSSkill('X3', 'X', 3, 'Self-help skills - eating'),
  new ABLLSSkill('X4', 'X', 4, 'Self-help skills - toileting'),
  new ABLLSSkill('X5', 'X', 5, 'Self-help skills - bathing'),
  new ABLLSSkill('X6', 'X', 6, 'Self-help skills - brushing teeth'),
  new ABLLSSkill('X7', 'X', 7, 'Self-help skills - combing hair'),
  new ABLLSSkill('X8', 'X', 8, 'Self-help skills - clipping nails'),
  new ABLLSSkill('X9', 'X', 9, 'Self-help skills - applying makeup'),
  new ABLLSSkill('X10', 'X', 10, 'Self-help skills - shaving'),
  new ABLLSSkill('X11', 'X', 11, 'Self-help skills - tying shoes'),
  new ABLLSSkill('X12', 'X', 12, 'Self-help skills - buttoning clothes'),
  new ABLLSSkill('X13', 'X', 13, 'Self-help skills - zipping clothes'),
  new ABLLSSkill('X14', 'X', 14, 'Self-help skills - putting on socks'),
  new ABLLSSkill('X15', 'X', 15, 'Self-help skills - putting on underwear'),
  new ABLLSSkill('X16', 'X', 16, 'Self-help skills - putting on shirts'),
  new ABLLSSkill('X17', 'X', 17, 'Self-help skills - putting on pants'),
  new ABLLSSkill('X18', 'X', 18, 'Self-help skills - putting on coats'),
  new ABLLSSkill('X19', 'X', 19, 'Self-help skills - putting on hats'),
  new ABLLSSkill('X20', 'X', 20, 'Self-help skills - putting on gloves'),
  new ABLLSSkill('X21', 'X', 21, 'Self-help skills - putting on scarves'),
  new ABLLSSkill('X22', 'X', 22, 'Self-help skills - putting on jewelry'),
  new ABLLSSkill('X23', 'X', 23, 'Self-help skills - putting on accessories'),
  new ABLLSSkill('X24', 'X', 24, 'Self-help skills - organizing belongings'),
  new ABLLSSkill('X25', 'X', 25, 'Self-help skills - maintaining personal space'),

  // Domain Y: Social Interaction Skills (Y1-Y28)
  new ABLLSSkill('Y1', 'Y', 1, 'Imitation of gross motor movements'),
  new ABLLSSkill('Y2', 'Y', 2, 'Imitation of fine motor movements'),
  new ABLLSSkill('Y3', 'Y', 3, 'Imitation of vocal-verbal behavior'),
  new ABLLSSkill('Y4', 'Y', 4, 'Imitation of actions with objects'),
  new ABLLSSkill('Y5', 'Y', 5, 'Imitation of actions in sequence'),
  new ABLLSSkill('Y6', 'Y', 6, 'Imitation of play actions'),
  new ABLLSSkill('Y7', 'Y', 7, 'Imitation of social interactions'),
  new ABLLSSkill('Y8', 'Y', 8, 'Initiates social interaction'),
  new ABLLSSkill('Y9', 'Y', 9, 'Maintains social interaction'),
  new ABLLSSkill('Y10', 'Y', 10, 'Terminates social interaction appropriately'),
  new ABLLSSkill('Y11', 'Y', 11, 'Responds to social initiations'),
  new ABLLSSkill('Y12', 'Y', 12, 'Shares enjoyment'),
  new ABLLSSkill('Y13', 'Y', 13, 'Shows empathy'),
  new ABLLSSkill('Y14', 'Y', 14, 'Takes turns'),
  new ABLLSSkill('Y15', 'Y', 15, 'Shares materials'),
  new ABLLSSkill('Y16', 'Y', 16, 'Cooperates with peers'),
  new ABLLSSkill('Y17', 'Y', 17, 'Plays cooperatively'),
  new ABLLSSkill('Y18', 'Y', 18, 'Engages in group activities'),
  new ABLLSSkill('Y19', 'Y', 19, 'Follows group instructions'),
  new ABLLSSkill('Y20', 'Y', 20, 'Participates in group discussions'),
  new ABLLSSkill('Y21', 'Y', 21, 'Respects personal space'),
  new ABLLSSkill('Y22', 'Y', 22, 'Uses appropriate volume'),
  new ABLLSSkill('Y23', 'Y', 23, 'Uses appropriate tone'),
  new ABLLSSkill('Y24', 'Y', 24, 'Uses appropriate gestures'),
  new ABLLSSkill('Y25', 'Y', 25, 'Uses appropriate facial expressions'),
  new ABLLSSkill('Y26', 'Y', 26, 'Uses appropriate eye contact'),
  new ABLLSSkill('Y27', 'Y', 27, 'Uses appropriate body language'),
  new ABLLSSkill('Y28', 'Y', 28, 'Uses appropriate social conventions'),

  // Domain Z: Motor Skills (Z1-Z28)
  new ABLLSSkill('Z1', 'Z', 1, 'Motor skills - gross motor - head control'),
  new ABLLSSkill('Z2', 'Z', 2, 'Motor skills - gross motor - sitting'),
  new ABLLSSkill('Z3', 'Z', 3, 'Motor skills - gross motor - crawling'),
  new ABLLSSkill('Z4', 'Z', 4, 'Motor skills - gross motor - standing'),
  new ABLLSSkill('Z5', 'Z', 5, 'Motor skills - gross motor - walking'),
  new ABLLSSkill('Z6', 'Z', 6, 'Motor skills - gross motor - running'),
  new ABLLSSkill('Z7', 'Z', 7, 'Motor skills - gross motor - jumping'),
  new ABLLSSkill('Z8', 'Z', 8, 'Motor skills - gross motor - hopping'),
  new ABLLSSkill('Z9', 'Z', 9, 'Motor skills - gross motor - skipping'),
  new ABLLSSkill('Z10', 'Z', 10, 'Motor skills - gross motor - galloping'),
  new ABLLSSkill('Z11', 'Z', 11, 'Motor skills - gross motor - sliding'),
  new ABLLSSkill('Z12', 'Z', 12, 'Motor skills - gross motor - swinging'),
  new ABLLSSkill('Z13', 'Z', 13, 'Motor skills - gross motor - climbing'),
  new ABLLSSkill('Z14', 'Z', 14, 'Motor skills - gross motor - balancing'),
  new ABLLSSkill('Z15', 'Z', 15, 'Motor skills - gross motor - catching'),
  new ABLLSSkill('Z16', 'Z', 16, 'Motor skills - gross motor - throwing'),
  new ABLLSSkill('Z17', 'Z', 17, 'Motor skills - gross motor - kicking'),
  new ABLLSSkill('Z18', 'Z', 18, 'Motor skills - gross motor - dribbling'),
  new ABLLSSkill('Z19', 'Z', 19, 'Motor skills - gross motor - striking'),
  new ABLLSSkill('Z20', 'Z', 20, 'Motor skills - gross motor - rolling'),
  new ABLLSSkill('Z21', 'Z', 21, 'Motor skills - gross motor - twisting'),
  new ABLLSSkill('Z22', 'Z', 22, 'Motor skills - gross motor - bending'),
  new ABLLSSkill('Z23', 'Z', 23, 'Motor skills - gross motor - stretching'),
  new ABLLSSkill('Z24', 'Z', 24, 'Motor skills - gross motor - reaching'),
  new ABLLSSkill('Z25', 'Z', 25, 'Motor skills - gross motor - grasping'),
  new ABLLSSkill('Z26', 'Z', 26, 'Motor skills - gross motor - manipulating'),
  new ABLLSSkill('Z27', 'Z', 27, 'Motor skills - gross motor - releasing'),
  new ABLLSSkill('Z28', 'Z', 28, 'Motor skills - gross motor - coordinated movements'),
];
